### ISSUE TITLE
PHP Fatal error when adding user or group

### ISSUE THREAD

**Issue by autious** [rafaelgou/php-apache2-basic-auth-manager#17]
When adding a user or group i get the following error in the apache error log: 

`[Wed Mar 21 10:27:26.529026 2018] [:error] [pid 27425] [client 89.233.217.40:24169] PHP Fatal error:  Uncaught Error: __clone method called on non-object in /var/www/dev/users/vendor/rafaelgou/php-apache2-basic-auth/src/Apache2BasicAuth/Service.php:311\nStack trace:\n#0 /var/www/dev/users/vendor/rafaelgou/php-apache2-basic-auth/src/Apache2BasicAuth/Service.php(384): Apache2BasicAuth\\Service->persistUser(Object(Apache2BasicAuth\\Model\\User))\n#1 /var/www/dev/users/src/App/Controller/User.php(47): Apache2BasicAuth\\Service->persist(Object(Apache2BasicAuth\\Model\\User))\n#2 /var/www/dev/users/vendor/symfony/http-kernel/HttpKernel.php(151): App\\Controller\\User->add(Object(Symfony\\Component\\HttpFoundation\\Request))\n#3 /var/www/dev/users/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\\Component\\HttpKernel\\HttpKernel->handleRaw(Object(Symfony\\Component\\HttpFoundation\\Request), 1)\n#4 /var/www/dev/users/vendor/silex/silex/src/Silex/Application.php(496): Symfony\\Component\\HttpKernel\\HttpKernel->handle(Object(Symfony\\Component\\HttpFoundation\\Request), 1, true)\n#5 /var/www/ in /var/www/dev/users/vendor/rafaelgou/php-apache2-basic-auth/src/Apache2BasicAuth/Service.php on line 311, referer: https://dev.site.net/users/user/add`

The htpasswd and htgroup files are both owned by the apache2 users (www-data) with user rw rights.

It's possible to open the add page, done using the previously mentioned rewrite configuration.

I've run 

`composer install` 

in the application folder to get everything running, i have no idea if this is intended because it's not mentioned in the readme.md and i have no previous experience with composer applications.

**Comment by iamambrus** [comment]
Have the same challenge, on windows. Is this permission related?

**Comment by Rillke** [comment]
Nope it isn't. The maintainer simply did not update `composer.lock` after [fixing](https://github.com/rafaelgou/php-apache2-basic-auth/commit/4061e16feb5197e7386e983e4df3716d128f4a48) the issue in the underlying library. The issue is that the code tries to clone something that doesn't exist.

This nicely formatted stack trace makes it easier to understand the issue:
```
#0 /var/www/html/php-apache2-basic-auth-manager/vendor/rafaelgou/php-apache2-basic-auth/src/Apache2BasicAuth/Service.php(384): Apache2BasicAuth\Service->persistUser(Object(Apache2BasicAuth\Model\User))
#1 /var/www/html/php-apache2-basic-auth-manager/src/App/Controller/User.php(47): Apache2BasicAuth\Service->persist(Object(Apache2BasicAuth\Model\User))
#2 [internal function]: App\Controller\User->add(Object(Symfony\Component\HttpFoundation\Request))
#3 /var/www/html/php-apache2-basic-auth-manager/vendor/symfony/http-kernel/HttpKernel.php(153): call_user_func_array(Array, Array)
#4 /var/www/html/php-apache2-basic-auth-manager/vendor/symfony/http-kernel/HttpKernel.php(68): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#5 /var/www/html/php-apache2-basic-auth-manager/ven in <b>/var/www/html/php-apache2-basic-auth-manager/vendor/rafaelgou/php-apache2-basic-auth/src/Apache2BasicAuth/Service.php</b> on line <b>311</b><br />
```
