### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by DanielRuf** [rafaelgou/php-apache2-basic-auth-manager#6]
- [ ] add composer.json
- [ ] create release(s)
- [ ] add version number to Composer file
- [ ] publish on [Packagist](https://packagist.org)
- [ ] manage dependencies using Bower

**Comment by rafaelgou** [comment]
Will do it!
Actually, make a rewrite with better practices.

**Comment by rafaelgou** [comment]
Just did a full rewrite.
