### ISSUE TITLE
Cannot modify header information - headers already sent

### ISSUE THREAD

**Issue by gcscaglia** [rafaelgou/php-apache2-basic-auth-manager#7]
When an user or group is added, the page will refresh to show something along the lines of:

```
Warning: Cannot modify header information - headers already sent by (output started at /var/www/html/admin/_header.php:36) in /var/www/html/admin/userAdd.php on line 33
```

The group/user will be added correctly, but the message causes confusion.

I may fix it and provide a PR, but I don't know when or if.

Meanwhile it is possible to remove the offending  `header()` call as an workaround; No message is better than misleading error message.

**Comment by rafaelgou** [comment]
Just fixed. 
But I'll do some refactor for better on this tiny project.

**Comment by rafaelgou** [comment]
I did a full rewrite. You can check it.
