### ISSUE TITLE
File /vendor/autoload.php missing

### ISSUE THREAD

**Issue by skrue** [rafaelgou/php-apache2-basic-auth-manager#8]
`PHP Fatal error:  require_once(): Failed opening required '/var/www/php-apache2-basic-auth-manager/web/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/php-apache2-basic-auth-manager/web/index.php on line 11`

The whole /vendor directory is missing. Commenting out line 11 in /web/index.php will obviously generate an error as well:

`PHP Fatal error:  Uncaught Error: Class 'Silex\\Application' not found in /var/www/php-apache2-basic-auth-manager/web/index.php:33
Stack trace:
#0 {main}
  thrown in /var/www/php-apache2-basic-auth-manager/web/index.php on line 33`

**Comment by rafaelgou** [comment]
Missing `composer install` on the install instructions.

I'll add that. For now, just run `composer install` to get dependencies. If you don't have `composer` installed please follow instructions from https://getcomposer.org/ .

**Comment by Rillke** [comment]
#22 for that.
